name: xerophagon-arm

on:
  push:
    branches:
      - arm
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write access to repository contents for release uploads
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        
    - name: Build
      run: |
        go mod init xerophagon
        CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -a -ldflags="-s -w" -o xerophagon-arm
        upx --best xerophagon-arm

    - name: Upload xerophagon as artifact
      uses: actions/upload-artifact@v4
      with:
        name: xerophagon-arm
        path: xerophagon-arm
    
    - name: Upload to GitHub Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: xerophagon-arm
        draft: true
